version: '3.8'

services:
  mongasite:
    build: .
    container_name: mongasite
    ports:
      - "5173:5173"
    networks:
      - cloudflare_network
    environment:
      - VITE_HOST=0.0.0.0
      
networks:
  cloudflare_network:
    driver: bridge
